name = "dotfiles"
id = "17504290032302696503"
default = "desktop"
systems = ["desktop", "laptop"]

[[links]]
name = "backgrounds"
destination = "$HOME/backgrounds"
src = "backgrounds"

[[links]]
name = ".config/nvim"
destination = "$HOME/.config/nvim"
src = ".config/nvim"

[[links]]
name = ".config/alacritty.yml"
destination = "$HOME/.config/alacritty.yml"
src = ".config/alacritty.yml"

[[links]]
name = ".config/rofi"
destination = "$HOME/.config/rofi.old"
src = ".config/rofi"

[[links]]
name = ".config/picom"
destination = "$HOME/.config/picom"
src = ".config/picom"

[[links]]
name = ".config/starship.toml"
destination = "$HOME/.config/starship.toml"
src = ".config/starship.toml"

[[links]]
name = "xmonad/my-xmonad.cabal"
destination = "$HOME/.xmonad/my-xmonad.cabal"
src = "xmonad/my-xmonad.cabal"

[[links]]
name = "xmonad/stack.yaml"
destination = "$HOME/.xmonad/stack.yaml"
src = ["desktop", "xmonad/stack.yaml"]

[[links]]
name = "xmonad/lib"
destination = "$HOME/.xmonad/lib"
src = "xmonad/lib"

[[links]]
name = "xmonad"
destination = "$HOME/.xmonad/xmonad.hs"
src = ["desktop", "xmonad/lib/xmonad.hs"]

[[links]]
name = ".config/polybar/config.ini"
destination = "$HOME/.config/polybar/config.ini"
src = ".config/polybar/config.ini"

[[links]]
name = ".config/polybar/launch_desktop.sh"
destination = "$HOME/.config/polybar/launch.sh"

[links.src]
desktop = ".config/polybar/launch_desktop.sh"
laptop = ".config/polybar/launch_laptop.sh"

[[links]]
name = ".config/polybar/scripts"
destination = "$HOME/.config/polybar/scripts"
src = ".config/polybar/scripts"

[[links]]
name = "xmonad/build"
destination = "$HOME/.xmonad/build"

[links.src]
laptop = "xmonad/build_laptop"
desktop = "xmonad/build_desktop"

[[links]]
name = "xmonad/screenshot-sec.sh"
destination = "$HOME/.xmonad/screenshot-sec.sh"
src = "xmonad/screenshot-sec.sh"

[[links]]
name = ".config/fontconfig"
destination = "$HOME/.config/fontconfig"
src = ".config/fontconfig"

[[links]]
name = "xmonad/my-xmonad_laptop.cabal"
destination = "$HOME/.xmonad/my-xmonad.cabal"

[links.src]
desktop = "xmonad/my-xmonad.cabal"
laptop = "xmonad/my-xmonad_laptop.cabal"

[[links]]
name = "dotfiles"
destination = "$HOME/.zshrc"
src = ".zshrc"

[[links]]
name = "dotfiles"
destination = "$HOME/.tmux"
src = ".tmux"

[[links]]
name = "dotfiles"
destination = "$HOME/.tmux.conf.local"
src = ".tmux.conf.local"

[[links]]
name = ".tmux"
destination = "$HOME/.tmux.conf"
src = ".tmux/tmux.conf"

[[links]]
name = ".config/dunst"
destination = "$HOME/.config/dunst"
src = ".config/dunst"

[[links]]
name = "phoebelyrics"
destination = "$HOME/Music/phoebe"
src = "phoebelyrics"

[[links]]
name = ".config/rofi_themed"
destination = "/home/auscyber/.config/rofi"
src = ".config/rofi_themed"
